/*  Qn :
    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2,the first 10 terms will be:
            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence
    whose values do not exceed the input integer, find the sum of the even-valued terms.

             Sample input         Sample output
                100                     44
*/

/*
    Author : Arnob Mahmud

    mail : arnob.tech.me@gmail.com
*/

#include <stdio.h>

int main(int argc, char const *argv[])
{
    int a = 1, b = 2, c = 0, n, sum = 0;

    printf("Enter n : ");
    scanf("%d", &n);

    printf("%d %d ", a, b);
    c = a + b;

    while (c <= n)
    {
        printf("%d ", c);
        a = b;
        b = c;
        c = a + b;

        if (a % 2 == 0)
        {
            sum += a;
        }
    }

    printf("\nSum : %d", sum);

    return 0;
}
